name: Action Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew & Build with Gradle
      run: chmod +x gradlew && ./gradlew build 
      
    - name: Getting… apk ready
      run: echo -e 'Building… APK'
    - uses: actions/upload-artifact@v2
      with:
        name: action done
        path: ./app/build/outputs/apk/debug/app-debug.apk
        
    - name: LS apk
      run: ls -a ./app/build/outputs/apk/debug && echo "" && ls -a ./app/build/outputs/apk/release
